### ISSUE TITLE
Error when try to download from github

### ISSUE THREAD

**Issue by joshualiuxu** [ghislainv/jSDM#10]
Hello Ghislain,
I dont know why found the compilation error when I try to download jSDM from github.

> devtools::install_github("ghislainv/jSDM")
Downloading GitHub repo ghislainv/jSDM@HEAD
√  checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpmQNpKq\remotesa01c738e284e\ghislainv-jSDM-7216a25/DESCRIPTION' ...
-  preparing 'jSDM': (369ms)
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'jSDM/vignettes/SDM_JSDM_files'
   Removed empty directory 'jSDM/vignettes/jSDM_boral_files'
   Removed empty directory 'jSDM/vignettes/jSDM_in_parallel_files'
-  looking to see if a 'data/datalist' file should be added
-  building 'jSDM_0.1.0.tar.gz'
   Warning: file 'jSDM/cleanup' did not have execute permissions: corrected
   
* installing *source* package 'jSDM' ...
** using staged installation
** libs

*** arch - i386
/mingw32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -I/include -I'C:/Program Files/R/R-4.0.2/library/Rcpp/include' -I'C:/Program Files/R/R-4.0.2/library/RcppArmadillo/include' -I'C:/Program Files/R/R-4.0.2/library/RcppGSL/include'     -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
In file included from C:/Program Files/R/R-4.0.2/library/RcppGSL/include/RcppGSL.h:25,
                 from RcppExports.cpp:5:
C:/Program Files/R/R-4.0.2/library/RcppGSL/include/RcppGSLForward.h:25:10: fatal error: gsl/gsl_vector.h: No such file or directory
 #include <gsl/gsl_vector.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.2/etc/i386/Makeconf:229: RcppExports.o] Error 1
ERROR: compilation failed for package 'jSDM'
* removing 'C:/Program Files/R/R-4.0.2/library/jSDM'
* restoring previous 'C:/Program Files/R/R-4.0.2/library/jSDM'
错误: Failed to install 'jSDM' from GitHub:
  (由警告转换成)installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpmQNpKq/filea01c3ff42276/jSDM_0.1.0.tar.gz’ had non-zero exit status](url)

The reason that I want to use github rather than Cran is jSDM from Cran may be lack of some code for example jSDM_binomial_probit_block. 
Can you help me? 
Look forward to your reply!
Thank you !

**Comment by ghislainv** [comment]
Hi Joshua,

Before using command devtools::install_github("ghislainv/jSDM"), be sure to:
- install Rtools <https://cran.r-project.org/bin/windows/Rtools/> to be able to compile packages
- install GSL on Windows. For example, use the pre-compile libraries local323.zip provided by Prof. Brian Ripley: http://www.stats.ox.ac.uk/pub/Rtools/libs.html
- set the correct path for LIB_GSL (eg. in R with Sys.setenv("LIB_GSL" = "C:/local323"))

We will try to udpate the Readme file for installation from github on Windows.

PS: Some info here might also help: https://stackoverflow.com/questions/23640088/setting-up-rcpp-gsl-for-windows/23640315#23640315

**Comment by joshualiuxu** [comment]
Thanks for your response.&nbsp; I will check it and try again.&nbsp;



---Original---

**Comment by JeanneClement** [comment]
Hi Joshua,
We udpated the Readme file for installation from github on Windows.
The binary release of jSDM compiled with R version 4.0.3 can be found here : 
https://nextcloud.fraisedesbois.net/index.php/s/bEQNBdwe2RCSK9F
