### ISSUE TITLE
Support for Omitting Site data  completely 

### ISSUE THREAD

**Issue by connor-klopfer** [ghislainv/jSDM#11]
Hello, 
Great package, thanks for sharing it. I was just wondering if this supports running the JDSM without including any site data?  More specifically, I'm looking to recreate something like the 'Unconstrained ordination' plot in Figure 2 from the Warton 2015 paper you reference in the reference docs. I tried including the site data as a single column intercept matrix, but I think your code is adding an additional intercept when running. I was just wondering if there was a more straightforward way to do this that I missed. Thanks.

**Comment by JeanneClement** [comment]
Hello, thanks for your feedback, after some corrections the package is now able to adjust JSDMs without including any site data, I recommend you to download the latest version available on Github. 
You have to include the site data as a matrix with a single column of 1 named "Int" for example and to specify the formula : " site_suitability=Int-1" to avoid the adding of an additional intercept when running.

Best regards
