### ISSUE TITLE
Estimation of Madagascar’s plant biodiversity-Raw data file

### ISSUE THREAD

**Issue by gujiqi** [ghislainv/jSDM#18]
Hi, I am a graduate student of China Agricultural University estimating its, mainly in Tibet for moss research. I am running the Estimation of Madagascar's plant biodiversity example, but I can't find the tiff and csv files inside the example. Where can I find these files, or if it is convenient, can you send them in my email to gujiqi1998@163.com. I would really like to run this code from start to finish, it is amazing. Thank you!

**Comment by JeanneClement** [comment]
Hi, sorry, I can't send you the Madagascar's data files. They are not open data but you can run the code using a forest inventory dataset and climate data that you have on hand.
